import { useState, useEffect } from "react";

const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export default function BookForm({ book, onSubmit, onCancel }) {
  const [form, setForm] = useState({
    title: "",
    author: "",
    email: "",
    age: "",
    publisher: "",
    publishedDate: "",
    description: ""
  });

  const [errors, setErrors] = useState({});

  // Helper function to convert date to YYYY-MM-DD format for date input
  const formatDateForInput = (dateString) => {
    if (!dateString) return "";
    
    // If it's already in YYYY-MM-DD format, return as is
    if (/^\d{4}-\d{2}-\d{2}$/.test(dateString)) {
      return dateString;
    }
    
    // If it's just a year (e.g., "2008"), convert to YYYY-01-01
    if (/^\d{4}$/.test(dateString)) {
      return `${dateString}-01-01`;
    }
    
    // Try to parse as date
    const date = new Date(dateString);
    if (!isNaN(date.getTime())) {
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      return `${year}-${month}-${day}`;
    }
    
    return "";
  };

  useEffect(() => {
    if (book) {
      setForm({
        title: book.title || "",
        author: book.author || "",
        email: book.email || "",
        age: book.age || "",
        publisher: book.publisher || "",
        publishedDate: formatDateForInput(book.publishedDate),
        description: book.description || "",
        id: book.id
      });
    } else {
      setForm({
        title: "",
        author: "",
        email: "",
        age: "",
        publisher: "",
        publishedDate: "",
        description: ""
      });
    }
    setErrors({});
  }, [book]);

  const validate = () => {
    let err = {};

    // Title validation - required string
    if (!form.title.trim()) {
      err.title = "Title is required";
    } else if (typeof form.title !== "string") {
      err.title = "Title must be a string";
    }

    // Author validation - required string
    if (!form.author.trim()) {
      err.author = "Author is required";
    } else if (typeof form.author !== "string") {
      err.author = "Author must be a string";
    }

    // Email validation - must be valid email format
    if (!form.email.trim()) {
      err.email = "Email is required";
    } else if (!emailRegex.test(form.email)) {
      err.email = "Please enter a valid email address";
    }

    // Age validation - must be a positive integer
    const ageNum = Number(form.age);
    if (!form.age || form.age.toString().trim() === "") {
      err.age = "Age is required";
    } else if (!Number.isInteger(ageNum) || ageNum <= 0) {
      err.age = "Age must be a positive integer";
    }

    // Publisher validation - optional string
    if (form.publisher && typeof form.publisher !== "string") {
      err.publisher = "Publisher must be a string";
    }

    // Published Date validation - optional date
    // Date input returns a string in YYYY-MM-DD format, which is valid

    // Description validation - optional string
    if (form.description && typeof form.description !== "string") {
      err.description = "Description must be a string";
    }

    setErrors(err);
    return Object.keys(err).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (validate()) {
      // Convert age to number before submitting
      // Remove id if it's a new book (id will be generated by the server)
      const submitData = {
        title: form.title,
        author: form.author,
        email: form.email,
        age: Number(form.age),
        publisher: form.publisher || "",
        publishedDate: form.publishedDate || "",
        description: form.description || ""
      };
      
      // Only include id if editing an existing book
      if (form.id) {
        submitData.id = form.id;
      }
      
      onSubmit(submitData);
    }
  };

  return (
    <form className="card p-3 mb-3" onSubmit={handleSubmit} style={{ maxHeight: "80vh", overflowY: "auto" }}>
      <h5 className="mb-3">{form.id ? "Edit Book" : "Add Book"}</h5>

      <div className="mb-3">
        <label className="form-label">Title *</label>
        <input
          type="text"
          className={`form-control ${errors.title ? "is-invalid" : ""}`}
          placeholder="Enter book title"
          value={form.title}
          onChange={e => setForm({ ...form, title: e.target.value })}
        />
        {errors.title && <div className="invalid-feedback">{errors.title}</div>}
      </div>

      <div className="mb-3">
        <label className="form-label">Author *</label>
        <input
          type="text"
          className={`form-control ${errors.author ? "is-invalid" : ""}`}
          placeholder="Enter author name"
          value={form.author}
          onChange={e => setForm({ ...form, author: e.target.value })}
        />
        {errors.author && <div className="invalid-feedback">{errors.author}</div>}
      </div>

      <div className="mb-3">
        <label className="form-label">Email *</label>
        <input
          type="email"
          className={`form-control ${errors.email ? "is-invalid" : ""}`}
          placeholder="Enter email address"
          value={form.email}
          onChange={e => setForm({ ...form, email: e.target.value })}
        />
        {errors.email && <div className="invalid-feedback">{errors.email}</div>}
      </div>

      <div className="mb-3">
        <label className="form-label">Age *</label>
        <input
          type="number"
          className={`form-control ${errors.age ? "is-invalid" : ""}`}
          placeholder="Enter age (positive integer)"
          value={form.age}
          onChange={e => setForm({ ...form, age: e.target.value })}
          min="1"
          step="1"
        />
        {errors.age && <div className="invalid-feedback">{errors.age}</div>}
      </div>

      <div className="mb-3">
        <label className="form-label">Publisher</label>
        <input
          type="text"
          className={`form-control ${errors.publisher ? "is-invalid" : ""}`}
          placeholder="Enter publisher name"
          value={form.publisher}
          onChange={e => setForm({ ...form, publisher: e.target.value })}
        />
        {errors.publisher && <div className="invalid-feedback">{errors.publisher}</div>}
      </div>

      <div className="mb-3">
        <label className="form-label">Published Date</label>
        <input
          type="date"
          className={`form-control ${errors.publishedDate ? "is-invalid" : ""}`}
          value={form.publishedDate}
          onChange={e => setForm({ ...form, publishedDate: e.target.value })}
        />
        {errors.publishedDate && <div className="invalid-feedback">{errors.publishedDate}</div>}
      </div>

      <div className="mb-3">
        <label className="form-label">Description/Overview</label>
        <textarea
          className={`form-control ${errors.description ? "is-invalid" : ""}`}
          placeholder="Enter book description or overview"
          value={form.description}
          onChange={e => setForm({ ...form, description: e.target.value })}
          rows="4"
        />
        {errors.description && <div className="invalid-feedback">{errors.description}</div>}
      </div>

      <div className="mt-3">
        <button type="submit" className="btn btn-success me-2">Save</button>
        <button type="button" className="btn btn-secondary" onClick={onCancel}>
          Cancel
        </button>
      </div>
    </form>
  );
}
